[project]
name = "homework-2-n8n-workflow"
version = "0.1.0"
description = "N8N workflow deployment for homework 2"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "requests>=2.28.0",
    "python-dotenv>=1.0.0"
]